### PR TITLE
Update and rename sv-SE.json to sv-NO.json

### PR DESCRIPTION
**Pull request by kongjudas**
Norwegian translation

### CODE REVIEW

**Comment by kongjudas** [comment]
Oops, left the "sv" in the title. Should be "no-NO"

**Comment by tuanha2000vn** [comment]
Thank you @kongjudas , new language added next update

Screenshot_1592163538

**Comment by kongjudas** [comment]
Cool, but it’s not Nynorsk, it’s Norwegian
________________________________
Fra: tuanha2000vn <notifications@github.com>
Sendt: søndag 14. juni 2020 21:40
Til: tuanha2000vn/Home-Assistant-Dashboard <Home-Assistant-Dashboard@noreply.github.com>
Kopi: kongjudas <kongjudas@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [tuanha2000vn/Home-Assistant-Dashboard] Update and rename sv-SE.json to sv-NO.json (#17)


Thank you @kongjudas<https://github.com/kongjudas> , new language added next update

[Screenshot_1592163538]<https://user-images.githubusercontent.com/2765517/84602425-8b6f6800-aeb1-11ea-9085-f51e023e5fa0.png>

**Comment by tuanha2000vn** [comment]
Thank, will change next update.

**Comment by tuanha2000vn** [comment]
Screenshot_1592558005

thank you @kongjudas, I hope it looking good by now.

**Pull request merged**
